#
#  Docker Compose file for deploying antimatter services.
#  Created On 03 October 2021
#

version: "2.1"
services:
    zoo-one:
        image: zookeeper:latest
        container_name: zoo-one
        restart: always
        hostname: zoo-one
        depends_on:
            - zoo-two
        ports:
            - 2181:2181
        environment:
            - ZOO_MY_ID=1
            - server.1=zoo-one:2888:3888;2181 server.2=zoo-two:2888:3888;2181 server.3=zoo-three:2888:3888;2181

    zoo-two:
        image: zookeeper:latest
        container_name: zoo-two
        restart: always
        hostname: zoo-two
        depends_on:
            - zoo-three
        ports:
            - 2182:2181
        environment:
            - ZOO_MY_ID=2
            - server.1=zoo-one:2888:3888;2181 server.2=zoo-two:2888:3888;2181 server.3=zoo-three:2888:3888;2181

    zoo-three:
        image: zookeeper:latest
        container_name: zoo-three
        restart: always
        hostname: zoo-three
        ports:
            - 2183:2181
        environment:
            - ZOO_MY_ID=3
            - server.1=zoo-one:2888:3888;2181 server.2=zoo-two:2888:3888;2181 server.3=zoo-three:2888:3888;2181

    clickhouse:
        image: yandex/clickhouse-server
        container_name: clickhouse
        restart: always
        depends_on:
            - zoo-one
            - zoo-two
            - zoo-three
        ports:
            - 8123:8123
        volumes:
            - ./clickhouse:/var/lib/clickhouse
            - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml

    postgres:
        image: postgres:9.6-alpine
        container_name: postgres
        restart: always
        volumes:
            - ./postgres:/var/lib/postgresql/data/pgdata
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_PASSWORD: UCDoCjYxCFWReZeyJjovrrfczXgvPnvB

    redis:
        image: redis:6.2.4-alpine
        container_name: redis
        restart: always
        volumes:
            - ./redis:/data

    jitsu:
        image: jitsucom/jitsu:latest
        container_name: jitsu
        restart: always
        depends_on:
            - redis
        ports:
            - 8000:8000
        environment:
            - REDIS_URL=redis://redis:6379
            - UI_AUTH_REFRESH_SECRET=ULWBZyNfBeXPPVbwsEwgNVezsbjjyVdq
            - UI_AUTH_ACCESS_SECRET=sNVPJZnQZLMpKXvVHfdHMnitNHsRmURC
        volumes:
            - ./jitsu/configurator:/home/configurator/data/logs
            - ./jitsu/events:/home/eventnative/data/logs/events
            - ./jitsu/login:/home/eventnative/data/logs

    sqlpad:
        image: sqlpad/sqlpad:latest
        container_name: sqlpad
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./sqlpad:/var/lib/sqlpad
        environment:
            - SQLPAD_AUTH_DISABLED=true
            - SQLPAD_AUTH_DISABLED_DEFAULT_ROLE=admin
            - SQLPAD_USERPASS_AUTH_DISABLED=true
            - SQLPAD_ADMIN_PASSWORD=5aWC9bWss2kZjr6MoowFokbPqrFEagts
            - SQLPAD_ADMIN=example@example.com

    cube:
        image: cubejs/cube
        restart: always
        ports:
            - 4000:4000
        volumes:
            - ./cube:/cube/conf
        environment:
            - CUBEJS_DEV_MODE=true

    trino:
        image: trinodb/trino
        container_name: trino
        restart: always
        ports:
            - 8080:8080

    metabase:
        image: metabase/metabase
        container_name: metabase
        restart: always
        ports:
            - 3001:3000
        volumes:
            - ./metabase:/metabase-data
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db
